//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisajesCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagen
    {
        public int imagen_id { get; set; }
        public string imagen_nombre { get; set; }
        public string imagen_ruta { get; set; }
        public string imagen_descripcion { get; set; }
        public System.DateTime imagen_create_at { get; set; }
        public Nullable<System.DateTime> imagen_update_at { get; set; }
        public int usuario_id_fk { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
