//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisajesCosteros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class paisammg_Entities : DbContext
    {
        public paisammg_Entities()
            : base("name=paisammg_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<PDF> PDF { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Video> Video { get; set; }
    }
}
