//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaisajesCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDF
    {
        public int pdf_id { get; set; }
        public string pdf_nombre { get; set; }
        public string pdf_ruta { get; set; }
        public string pdf_descripcion { get; set; }
        public System.DateTime pdf_create_at { get; set; }
        public Nullable<System.DateTime> pdf_update_at { get; set; }
        public int usuario_id_fk { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
